<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.github.imrafaelmerino</groupId>
    <artifactId>java-fun</artifactId>
    <packaging>jar</packaging>
    <version>4.0.0-SNAPSHOT</version>
    <name>java-fun</name>
    <description>Some patterns and idioms from Functional Programming implemented in Java</description>
    <url>https://github.com/imrafaelmerino/java-fun</url>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>imrafaelmerino</id>
            <name>Rafael Merino García</name>
            <email>imrafael.merino@gmail.com</email>
        </developer>
    </developers>
    <scm>
        <url>https://github.com/imrafaelmerino/java-fun.git</url>
    </scm>
    <properties>
        <error-prone.version>2.36.0</error-prone.version>
        <NEXUS-STAGING-MAVEN-PLUGIN.VERSION>1.7.0</NEXUS-STAGING-MAVEN-PLUGIN.VERSION>
        <MAVEN-GPG-PLUGIN.VERSION>3.2.8</MAVEN-GPG-PLUGIN.VERSION>
        <MAVEN-SOURCE-PLUGIN.VERSION>3.4.0</MAVEN-SOURCE-PLUGIN.VERSION>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <MAVEN-COMPILER-PLUGIN.VERSION>3.15.0</MAVEN-COMPILER-PLUGIN.VERSION>
        <MAVEN-COMPILER-PLUGIN.RELEASE>21</MAVEN-COMPILER-PLUGIN.RELEASE>
        <MAVEN-SUREFIRE-PLUGIN.VERSION>3.5.5</MAVEN-SUREFIRE-PLUGIN.VERSION>
        <MAVEN-JAR-PLUGIN.VERSION>3.5.0</MAVEN-JAR-PLUGIN.VERSION>
        <MAVEN-JAVADOC-PLUGIN.VERSION>3.12.0</MAVEN-JAVADOC-PLUGIN.VERSION>
        <MAVEN-JACOCO-PLUGIN.VERSION>0.8.12</MAVEN-JACOCO-PLUGIN.VERSION>
        <MAVEN-ENFORCER-PLUGIN.VERSION>3.5.0</MAVEN-ENFORCER-PLUGIN.VERSION>
        <MAVEN-MINIMUM-VERSION>3.6.3</MAVEN-MINIMUM-VERSION>
        <JAVA-MINIMUM-VERSION>21</JAVA-MINIMUM-VERSION>
        <JAVAFUN.STATS.ENABLED>false</JAVAFUN.STATS.ENABLED>
        <JAVAFUN.STATS.VERBOSE>false</JAVAFUN.STATS.VERBOSE>
        <JAVAFUN.TEST.INCLUDED.TAGS></JAVAFUN.TEST.INCLUDED.TAGS>
        <JAVAFUN.TEST.EXCLUDED.TAGS>stats</JAVAFUN.TEST.EXCLUDED.TAGS>
        <JAVAFUN.COVERAGE.MIN.INSTRUCTION>0.50</JAVAFUN.COVERAGE.MIN.INSTRUCTION>
        <JAVAFUN.COVERAGE.MIN.BRANCH>0.35</JAVAFUN.COVERAGE.MIN.BRANCH>
        <APACHE_JMETER_CORE.VERSION>5.6.3</APACHE_JMETER_CORE.VERSION>
        <JUNIT-JUPITER-API.VERSION>5.11.3</JUNIT-JUPITER-API.VERSION>
        <JSON-VALUES.VERSION>14.0.0</JSON-VALUES.VERSION>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${JUNIT-JUPITER-API.VERSION}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>${MAVEN-ENFORCER-PLUGIN.VERSION}</version>
                <executions>
                    <execution>
                        <id>enforce-build-requirements</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>[${MAVEN-MINIMUM-VERSION},)</version>
                                </requireMavenVersion>
                                <requireJavaVersion>
                                    <version>[${JAVA-MINIMUM-VERSION},)</version>
                                </requireJavaVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <version>${MAVEN-COMPILER-PLUGIN.VERSION}</version>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <release>${MAVEN-COMPILER-PLUGIN.RELEASE}</release>
                    <showWarnings>true</showWarnings>
                    <encoding>UTF-8</encoding>
                    <testExcludes>
                        <testExclude>**/fun/jmeter/**</testExclude>
                    </testExcludes>
                    <compilerArgs>
                        <arg>-XDcompilePolicy=simple</arg>
                        <arg>--should-stop=ifError=FLOW</arg>
                        <arg>-Xplugin:ErrorProne -Xep:DeadException:WARN -Xep:GuardedBy:OFF</arg>
                        <arg>-Xlint:unchecked</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.errorprone</groupId>
                            <artifactId>error_prone_core</artifactId>
                            <version>${error-prone.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${MAVEN-SUREFIRE-PLUGIN.VERSION}</version>
                <configuration>
                    <groups>${JAVAFUN.TEST.INCLUDED.TAGS}</groups>
                    <excludedGroups>${JAVAFUN.TEST.EXCLUDED.TAGS}</excludedGroups>
                    <systemPropertyVariables>
                        <javafun.stats>${JAVAFUN.STATS.ENABLED}</javafun.stats>
                        <javafun.stats.verbose>${JAVAFUN.STATS.VERBOSE}</javafun.stats.verbose>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${MAVEN-JACOCO-PLUGIN.VERSION}</version>
                <configuration>
                    <rules>
                        <rule>
                            <element>BUNDLE</element>
                            <limits>
                                <limit>
                                    <counter>INSTRUCTION</counter>
                                    <value>COVEREDRATIO</value>
                                    <minimum>${JAVAFUN.COVERAGE.MIN.INSTRUCTION}</minimum>
                                </limit>
                                <limit>
                                    <counter>BRANCH</counter>
                                    <value>COVEREDRATIO</value>
                                    <minimum>${JAVAFUN.COVERAGE.MIN.BRANCH}</minimum>
                                </limit>
                            </limits>
                        </rule>
                    </rules>
                </configuration>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${MAVEN-JAR-PLUGIN.VERSION}</version>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Automatic-Module-Name>java_fun</Automatic-Module-Name>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${MAVEN-JAVADOC-PLUGIN.VERSION}</version>
                <configuration>
                    <source>${MAVEN-COMPILER-PLUGIN.RELEASE}</source>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>stats</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <JAVAFUN.STATS.ENABLED>true</JAVAFUN.STATS.ENABLED>
                <JAVAFUN.TEST.INCLUDED.TAGS>stats</JAVAFUN.TEST.INCLUDED.TAGS>
                <JAVAFUN.TEST.EXCLUDED.TAGS></JAVAFUN.TEST.EXCLUDED.TAGS>
            </properties>
        </profile>
        <profile>
            <id>jmeter-example</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>org.apache.jmeter</groupId>
                    <artifactId>ApacheJMeter_core</artifactId>
                    <version>${APACHE_JMETER_CORE.VERSION}</version>
                    <scope>test</scope>
                </dependency>
                <dependency>
                    <groupId>com.github.imrafaelmerino</groupId>
                    <artifactId>json-values</artifactId>
                    <version>${JSON-VALUES.VERSION}</version>
                    <scope>test</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>com.github.imrafaelmerino</groupId>
                            <artifactId>java-fun</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <testExcludes combine.self="override"/>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>local</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <distributionManagement>
                <repository>
                    <id>releases</id>
                    <name>Repositorio de releases</name>
                    <url>http://127.0.0.1:8081/repository/maven-releases/</url>
                </repository>
                <snapshotRepository>
                    <id>snapshots</id>
                    <name>Repositorio de snapshots</name>
                    <url>http://127.0.0.1:8081/repository/maven-snapshots/</url>
                </snapshotRepository>
            </distributionManagement>
        </profile>
        <profile>
            <id>release</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <distributionManagement>
                <snapshotRepository>
                    <id>ossrh</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                </snapshotRepository>
                <repository>
                    <id>ossrh</id>
                    <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
                </repository>
            </distributionManagement>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.plugins</groupId>
                        <artifactId>nexus-staging-maven-plugin</artifactId>
                        <version>${NEXUS-STAGING-MAVEN-PLUGIN.VERSION}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <serverId>ossrh</serverId>
                            <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                            <autoReleaseAfterClose>true</autoReleaseAfterClose>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${MAVEN-GPG-PLUGIN.VERSION}</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>${MAVEN-SOURCE-PLUGIN.VERSION}</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
