package jsonvalues.spec;

public enum ERROR_CODE
{
  STRING_EXPECTED,
  STRING_CONDITION,
  INT_EXPECTED,
  INT_CONDITION,
  LONG_EXPECTED,
  LONG_CONDITION,
  BOOLEAN_EXPECTED,
  BOOLEAN_CONDITION,
  INTEGRAL_EXPECTED,
  INTEGRAL_CONDITION,
  DECIMAL_EXPECTED,
  DECIMAL_CONDITION,
  TRUE_EXPECTED,
  FALSE_EXPECTED,
  OBJ_EXPECTED,
  OBJ_CONDITION,
  ARRAY_EXPECTED,
  ARRAY_CONDITION,
  NULL,
  REQUIRED,
  VALUE_CONDITION
}
